CREATE TABLE IF NOT EXISTS COUNTRIES(
	id int(11) PRIMARY KEY AUTO_INCREMENT,
    country_name varchar(100) NOT NULL
);

INSERT INTO countries(country_name) VALUES ('Afghanistan');
INSERT INTO countries(country_name) VALUES ('Albania');
INSERT INTO countries(country_name) VALUES ('Algeria');
INSERT INTO countries(country_name) VALUES ('American Samoa');
INSERT INTO countries(country_name) VALUES ('Andorra');
INSERT INTO countries(country_name) VALUES ('Angola');
INSERT INTO countries(country_name) VALUES ('Anguilla');
INSERT INTO countries(country_name) VALUES ('Antarctica');
INSERT INTO countries(country_name) VALUES ('Antigua and Barbuda');
INSERT INTO countries(country_name) VALUES ('Argentina');
INSERT INTO countries(country_name) VALUES ('Armenia');
INSERT INTO countries(country_name) VALUES ('Aruba');
INSERT INTO countries(country_name) VALUES ('Australia');
INSERT INTO countries(country_name) VALUES ('Austria');
INSERT INTO countries(country_name) VALUES ('Azerbaijan');
INSERT INTO countries(country_name) VALUES ('Bahamas');
INSERT INTO countries(country_name) VALUES ('Bahrain');
INSERT INTO countries(country_name) VALUES ('Bangladesh');
INSERT INTO countries(country_name) VALUES ('Barbados');
INSERT INTO countries(country_name) VALUES ('Belarus');
INSERT INTO countries(country_name) VALUES ('Belgium');
INSERT INTO countries(country_name) VALUES ('Belize');
INSERT INTO countries(country_name) VALUES ('Benin');
INSERT INTO countries(country_name) VALUES ('Bermuda');
INSERT INTO countries(country_name) VALUES ('Bhutan');
INSERT INTO countries(country_name) VALUES ('Bolivia');
INSERT INTO countries(country_name) VALUES ('Bosnia and Herzegovina');
INSERT INTO countries(country_name) VALUES ('Botswana');
INSERT INTO countries(country_name) VALUES ('Bouvet Island');
INSERT INTO countries(country_name) VALUES ('Brazil');
INSERT INTO countries(country_name) VALUES ('British Indian Ocean Territory');
INSERT INTO countries(country_name) VALUES ('Brunei Darussalam');
INSERT INTO countries(country_name) VALUES ('Bulgaria');
INSERT INTO countries(country_name) VALUES ('Burkina Faso');
INSERT INTO countries(country_name) VALUES ('Burundi');
INSERT INTO countries(country_name) VALUES ('Cambodia');
INSERT INTO countries(country_name) VALUES ('Cameroon');
INSERT INTO countries(country_name) VALUES ('Canada');
INSERT INTO countries(country_name) VALUES ('Cape Verde');
INSERT INTO countries(country_name) VALUES ('Cayman Islands');
INSERT INTO countries(country_name) VALUES ('Central African Republic');
INSERT INTO countries(country_name) VALUES ('Chad');
INSERT INTO countries(country_name) VALUES ('Chile');
INSERT INTO countries(country_name) VALUES ('China');
INSERT INTO countries(country_name) VALUES ('Christmas Island');
INSERT INTO countries(country_name) VALUES ('Cocos (Keeling) Islands');
INSERT INTO countries(country_name) VALUES ('Colombia');
INSERT INTO countries(country_name) VALUES ('Comoros');
INSERT INTO countries(country_name) VALUES ('Congo');
INSERT INTO countries(country_name) VALUES ('Cook Islands');
INSERT INTO countries(country_name) VALUES ('Costa Rica');
INSERT INTO countries(country_name) VALUES ('Croatia (Hrvatska)');
INSERT INTO countries(country_name) VALUES ('Cuba');
INSERT INTO countries(country_name) VALUES ('Cyprus');
INSERT INTO countries(country_name) VALUES ('Czech Republic');
INSERT INTO countries(country_name) VALUES ('Denmark');
INSERT INTO countries(country_name) VALUES ('Djibouti');
INSERT INTO countries(country_name) VALUES ('Dominica');
INSERT INTO countries(country_name) VALUES ('Dominican Republic');
INSERT INTO countries(country_name) VALUES ('East Timor');
INSERT INTO countries(country_name) VALUES ('Ecuador');
INSERT INTO countries(country_name) VALUES ('Egypt');
INSERT INTO countries(country_name) VALUES ('El Salvador');
INSERT INTO countries(country_name) VALUES ('Equatorial Guinea');
INSERT INTO countries(country_name) VALUES ('Eritrea');
INSERT INTO countries(country_name) VALUES ('Estonia');
INSERT INTO countries(country_name) VALUES ('Ethiopia');
INSERT INTO countries(country_name) VALUES ('Falkland Islands (Malvinas)');
INSERT INTO countries(country_name) VALUES ('Faroe Islands');
INSERT INTO countries(country_name) VALUES ('Fiji');
INSERT INTO countries(country_name) VALUES ('Finland');
INSERT INTO countries(country_name) VALUES ('France');
INSERT INTO countries(country_name) VALUES ('France, Metropolitan');
INSERT INTO countries(country_name) VALUES ('French Guiana');
INSERT INTO countries(country_name) VALUES ('French Polynesia');
INSERT INTO countries(country_name) VALUES ('French Southern Territories');
INSERT INTO countries(country_name) VALUES ('Gabon');
INSERT INTO countries(country_name) VALUES ('Gambia');
INSERT INTO countries(country_name) VALUES ('Georgia');
INSERT INTO countries(country_name) VALUES ('Germany');
INSERT INTO countries(country_name) VALUES ('Ghana');
INSERT INTO countries(country_name) VALUES ('Gibraltar');
INSERT INTO countries(country_name) VALUES ('Guernsey');
INSERT INTO countries(country_name) VALUES ('Greece');
INSERT INTO countries(country_name) VALUES ('Greenland');
INSERT INTO countries(country_name) VALUES ('Grenada');
INSERT INTO countries(country_name) VALUES ('Guadeloupe');
INSERT INTO countries(country_name) VALUES ('Guam');
INSERT INTO countries(country_name) VALUES ('Guatemala');
INSERT INTO countries(country_name) VALUES ('Guinea');
INSERT INTO countries(country_name) VALUES ('Guinea-Bissau');
INSERT INTO countries(country_name) VALUES ('Guyana');
INSERT INTO countries(country_name) VALUES ('Haiti');
INSERT INTO countries(country_name) VALUES ('Heard and Mc Donald Islands');
INSERT INTO countries(country_name) VALUES ('Honduras');
INSERT INTO countries(country_name) VALUES ('Hong Kong');
INSERT INTO countries(country_name) VALUES ('Hungary');
INSERT INTO countries(country_name) VALUES ('Iceland');
INSERT INTO countries(country_name) VALUES ('India');
INSERT INTO countries(country_name) VALUES ('Isle of Man');
INSERT INTO countries(country_name) VALUES ('Indonesia');
INSERT INTO countries(country_name) VALUES ('Iran (Islamic Republic of)');
INSERT INTO countries(country_name) VALUES ('Iraq');
INSERT INTO countries(country_name) VALUES ('Ireland');
INSERT INTO countries(country_name) VALUES ('Israel');
INSERT INTO countries(country_name) VALUES ('Italy');
INSERT INTO countries(country_name) VALUES ('Ivory Coast');
INSERT INTO countries(country_name) VALUES ('Jersey');
INSERT INTO countries(country_name) VALUES ('Jamaica');
INSERT INTO countries(country_name) VALUES ('Japan');
INSERT INTO countries(country_name) VALUES ('Jordan');
INSERT INTO countries(country_name) VALUES ('Kazakhstan');
INSERT INTO countries(country_name) VALUES ('Kenya');
INSERT INTO countries(country_name) VALUES ('Kiribati');
INSERT INTO countries(country_name) VALUES ('Korea, Democratic People''s Republic of');
INSERT INTO countries(country_name) VALUES ('Korea, Republic of');
INSERT INTO countries(country_name) VALUES ('Kosovo');
INSERT INTO countries(country_name) VALUES ('Kuwait');
INSERT INTO countries(country_name) VALUES ('Kyrgyzstan');
INSERT INTO countries(country_name) VALUES ('Lao People''s Democratic Republic');
INSERT INTO countries(country_name) VALUES ('Latvia');
INSERT INTO countries(country_name) VALUES ('Lebanon');
INSERT INTO countries(country_name) VALUES ('Lesotho');
INSERT INTO countries(country_name) VALUES ('Liberia');
INSERT INTO countries(country_name) VALUES ('Libyan Arab Jamahiriya');
INSERT INTO countries(country_name) VALUES ('Liechtenstein');
INSERT INTO countries(country_name) VALUES ('Lithuania');
INSERT INTO countries(country_name) VALUES ('Luxembourg');
INSERT INTO countries(country_name) VALUES ('Macau');
INSERT INTO countries(country_name) VALUES ('Macedonia');
INSERT INTO countries(country_name) VALUES ('Madagascar');
INSERT INTO countries(country_name) VALUES ('Malawi');
INSERT INTO countries(country_name) VALUES ('Malaysia');
INSERT INTO countries(country_name) VALUES ('Maldives');
INSERT INTO countries(country_name) VALUES ('Mali');
INSERT INTO countries(country_name) VALUES ('Malta');
INSERT INTO countries(country_name) VALUES ('Marshall Islands');
INSERT INTO countries(country_name) VALUES ('Martinique');
INSERT INTO countries(country_name) VALUES ('Mauritania');
INSERT INTO countries(country_name) VALUES ('Mauritius');
INSERT INTO countries(country_name) VALUES ('Mayotte');
INSERT INTO countries(country_name) VALUES ('Mexico');
INSERT INTO countries(country_name) VALUES ('Micronesia, Federated States of');
INSERT INTO countries(country_name) VALUES ('Moldova, Republic of');
INSERT INTO countries(country_name) VALUES ('Monaco');
INSERT INTO countries(country_name) VALUES ('Mongolia');
INSERT INTO countries(country_name) VALUES ('Montenegro');
INSERT INTO countries(country_name) VALUES ('Montserrat');
INSERT INTO countries(country_name) VALUES ('Morocco');
INSERT INTO countries(country_name) VALUES ('Mozambique');
INSERT INTO countries(country_name) VALUES ('Myanmar');
INSERT INTO countries(country_name) VALUES ('Namibia');
INSERT INTO countries(country_name) VALUES ('Nauru');
INSERT INTO countries(country_name) VALUES ('Nepal');
INSERT INTO countries(country_name) VALUES ('Netherlands');
INSERT INTO countries(country_name) VALUES ('Netherlands Antilles');
INSERT INTO countries(country_name) VALUES ('New Caledonia');
INSERT INTO countries(country_name) VALUES ('New Zealand');
INSERT INTO countries(country_name) VALUES ('Nicaragua');
INSERT INTO countries(country_name) VALUES ('Niger');
INSERT INTO countries(country_name) VALUES ('Nigeria');
INSERT INTO countries(country_name) VALUES ('Niue');
INSERT INTO countries(country_name) VALUES ('Norfolk Island');
INSERT INTO countries(country_name) VALUES ('Northern Mariana Islands');
INSERT INTO countries(country_name) VALUES ('Norway');
INSERT INTO countries(country_name) VALUES ('Oman');
INSERT INTO countries(country_name) VALUES ('Pakistan');
INSERT INTO countries(country_name) VALUES ('Palau');
INSERT INTO countries(country_name) VALUES ('Palestine');
INSERT INTO countries(country_name) VALUES ('Panama');
INSERT INTO countries(country_name) VALUES ('Papua New Guinea');
INSERT INTO countries(country_name) VALUES ('Paraguay');
INSERT INTO countries(country_name) VALUES ('Peru');
INSERT INTO countries(country_name) VALUES ('Philippines');
INSERT INTO countries(country_name) VALUES ('Pitcairn');
INSERT INTO countries(country_name) VALUES ('Poland');
INSERT INTO countries(country_name) VALUES ('Portugal');
INSERT INTO countries(country_name) VALUES ('Puerto Rico');
INSERT INTO countries(country_name) VALUES ('Qatar');
INSERT INTO countries(country_name) VALUES ('Reunion');
INSERT INTO countries(country_name) VALUES ('Romania');
INSERT INTO countries(country_name) VALUES ('Russian Federation');
INSERT INTO countries(country_name) VALUES ('Rwanda');
INSERT INTO countries(country_name) VALUES ('Saint Kitts and Nevis');
INSERT INTO countries(country_name) VALUES ('Saint Lucia');
INSERT INTO countries(country_name) VALUES ('Saint Vincent and the Grenadines');
INSERT INTO countries(country_name) VALUES ('Samoa');
INSERT INTO countries(country_name) VALUES ('San Marino');
INSERT INTO countries(country_name) VALUES ('Sao Tome and Principe');
INSERT INTO countries(country_name) VALUES ('Saudi Arabia');
INSERT INTO countries(country_name) VALUES ('Senegal');
INSERT INTO countries(country_name) VALUES ('Serbia');
INSERT INTO countries(country_name) VALUES ('Seychelles');
INSERT INTO countries(country_name) VALUES ('Sierra Leone');
INSERT INTO countries(country_name) VALUES ('Singapore');
INSERT INTO countries(country_name) VALUES ('Slovakia');
INSERT INTO countries(country_name) VALUES ('Slovenia');
INSERT INTO countries(country_name) VALUES ('Solomon Islands');
INSERT INTO countries(country_name) VALUES ('Somalia');
INSERT INTO countries(country_name) VALUES ('South Africa');
INSERT INTO countries(country_name) VALUES ('South Georgia South Sandwich Islands');
INSERT INTO countries(country_name) VALUES ('Spain');
INSERT INTO countries(country_name) VALUES ('Sri Lanka');
INSERT INTO countries(country_name) VALUES ('St. Helena');
INSERT INTO countries(country_name) VALUES ('St. Pierre and Miquelon');
INSERT INTO countries(country_name) VALUES ('SD', 'Sudan');
INSERT INTO countries(country_name) VALUES ('Suriname');
INSERT INTO countries(country_name) VALUES ('Svalbard and Jan Mayen Islands');
INSERT INTO countries(country_name) VALUES ('Swaziland');
INSERT INTO countries(country_name) VALUES ('Sweden');
INSERT INTO countries(country_name) VALUES ('Switzerland');
INSERT INTO countries(country_name) VALUES ('Syrian Arab Republic');
INSERT INTO countries(country_name) VALUES ('Taiwan');
INSERT INTO countries(country_name) VALUES ('Tajikistan');
INSERT INTO countries(country_name) VALUES ('Tanzania, United Republic of');
INSERT INTO countries(country_name) VALUES ('Thailand');
INSERT INTO countries(country_name) VALUES ('Togo');
INSERT INTO countries(country_name) VALUES ('Tokelau');
INSERT INTO countries(country_name) VALUES ('Tonga');
INSERT INTO countries(country_name) VALUES ('Trinidad and Tobago');
INSERT INTO countries(country_name) VALUES ('Tunisia');
INSERT INTO countries(country_name) VALUES ('Turkey');
INSERT INTO countries(country_name) VALUES ('Turkmenistan');
INSERT INTO countries(country_name) VALUES ('Turks and Caicos Islands');
INSERT INTO countries(country_name) VALUES ('Tuvalu');
INSERT INTO countries(country_name) VALUES ('Uganda');
INSERT INTO countries(country_name) VALUES ('Ukraine');
INSERT INTO countries(country_name) VALUES ('United Arab Emirates');
INSERT INTO countries(country_name) VALUES ('United Kingdom');
INSERT INTO countries(country_name) VALUES ('United States');
INSERT INTO countries(country_name) VALUES ('United States minor outlying islands');
INSERT INTO countries(country_name) VALUES ('Uruguay');
INSERT INTO countries(country_name) VALUES ('Uzbekistan');
INSERT INTO countries(country_name) VALUES ('Vanuatu');
INSERT INTO countries(country_name) VALUES ('Vatican City State');
INSERT INTO countries(country_name) VALUES ('Venezuela');
INSERT INTO countries(country_name) VALUES ('Vietnam');
INSERT INTO countries(country_name) VALUES ('Virgin Islands (British)');
INSERT INTO countries(country_name) VALUES ('Virgin Islands (U.S.)');
INSERT INTO countries(country_name) VALUES ('Wallis and Futuna Islands');
INSERT INTO countries(country_name) VALUES ('Western Sahara');
INSERT INTO countries(country_name) VALUES ('Yemen');
INSERT INTO countries(country_name) VALUES ('Yugoslavia');
INSERT INTO countries(country_name) VALUES ('Zaire');
INSERT INTO countries(country_name) VALUES ('Zambia');
INSERT INTO countries(country_name) VALUES ('Zimbabwe');